post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
  
          ## dart: PermissionGroup.camera
           'PERMISSION_CAMERA=1',
  
          ## dart: PermissionGroup.photos
           'PERMISSION_PHOTOS=1',
        ]
  
      end
      # End of the permission_handler configuration
    end
  end